

#include "CLK.h"

void INIT_CLK(void){
    SYSCTL_MOSCCTL_R &= ~SYSCTL_MOSCCTL_NOXTAL;
    SYSCTL_MOSCCTL_R &= ~SYSCTL_MOSCCTL_PWRDN;

    while(!(SYSCTL_RIS_R & SYSCTL_RIS_MOSCPUPRIS));         //wait for Osc. to be stabilized
    SYSCTL_RSCLKCFG_R |= 3 << SYSCTL_RSCLKCFG_OSCSRC_S;     //main

    SYSCTL_MEMTIM0_R |= 1 << SYSCTL_MEMTIM0_EWS_S | 1 << SYSCTL_MEMTIM0_FWS_S
            | 2 << SYSCTL_MEMTIM0_FBCHT_S | 2 << SYSCTL_MEMTIM0_EBCHT_S;

    SYSCTL_RSCLKCFG_R |= SYSCTL_RSCLKCFG_MEMTIMU;
}
